client:
  server_ip : localhost
  server_port : 2000
  default_dev : 1

device1:
  name : "Master 9"
  button1 : "Volume Up"
  button2 : "Volume Down"
  button3 : "Mute"

device2:
  name : "Refrence 5.32"
  button1 : "Gain high/low"
  button2 : "USB input"
  button3 : "Optical input"
