client:
  server_ip : localhost
  server_port : 2000
  default_dev : 1

device1:
  name : "Device1"
  button1 : "Volume Up"
  button2 : "Volume Down"
  button3 : "Mute"

device2:
  name : "Device2"
  button1 : "Oversampling"
  button2 : "Filter"
  button3 : "input"
